### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/apps/deliveryTest/recordData/logs/1106_64mbuff_poll0_msgtmout3000.log'

### ISSUE THREAD

**Issue by ShuxianMa** [woohan/kafkaTestScripts#1]
运行/home/apps/deliveryTest/autoTest1.py 脚本时报错：
```
Traceback (most recent call last):
  File "/home/apps/deliveryTest/autoTest1.py", line 20, in <module>
    hd1 = logging.FileHandler("/home/apps/deliveryTest/recordData/logs/"+logFileName+".log")
  File "/usr/lib/python3.6/logging/__init__.py", line 1032, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python3.6/logging/__init__.py", line 1061, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: '/home/apps/deliveryTest/recordData/logs/1106_64mbuff_poll0_msgtmout3000.log'
```
请问log文件怎么生成呢？

**Comment by woohan** [comment]
需要先手动创建对应的文件夹才行。
